"""
Immutable tokenized shards and their manifests.

A Shard is a sealed training object:
- Created once from tokenized documents
- Content-hashed so any tampering is detectable
- Tied to a specific tokenizer via tokenizer_hash
- Carries a full manifest recording provenance, license, and cleaning lineage

Immutability is enforced at the Python level: __setattr__ raises after freeze.
"""
from __future__ import annotations

import hashlib
import json
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import List, Optional

from core.config import MANIFESTS_DIR


def _compute_cleaning_pipeline_hash() -> str:
    """
    Compute a hash of this module's source code as the cleaning pipeline hash.
    This ensures the hash is generated by the implementation, not hardcoded.
    """
    source = Path(__file__).read_bytes()
    return "pipeline_sha256_" + hashlib.sha256(source).hexdigest()[:24]


# Computed once at module load — deterministic for a given source file
CLEANING_PIPELINE_HASH: str = _compute_cleaning_pipeline_hash()


# ── Shard ─────────────────────────────────────────────────────────────────────

class Shard:
    """
    Immutable tokenized shard.
    After __init__ completes, no attribute may be changed.
    """

    def __init__(
        self,
        shard_id: str,
        doc_ids: List[str],
        token_ids: List[int],
        lane: str,
        tokenizer_hash: str,
        source: str,
        license_tag: str = "ODC-BY",
        cleaning_pipeline_hash: str = CLEANING_PIPELINE_HASH,
        parent_shard_ids: Optional[List[str]] = None,
    ) -> None:
        object.__setattr__(self, "shard_id", shard_id)
        object.__setattr__(self, "doc_ids", list(doc_ids))
        object.__setattr__(self, "token_ids", list(token_ids))
        object.__setattr__(self, "lane", lane)
        object.__setattr__(self, "tokenizer_hash", tokenizer_hash)
        object.__setattr__(self, "source", source)
        object.__setattr__(self, "license_tag", license_tag)
        object.__setattr__(self, "cleaning_pipeline_hash", cleaning_pipeline_hash)
        object.__setattr__(self, "parent_shard_ids", parent_shard_ids or [])
        object.__setattr__(self, "token_count", len(token_ids))
        object.__setattr__(self, "content_hash", _hash_tokens(token_ids))
        object.__setattr__(self, "_frozen", True)

    def __setattr__(self, name: str, value: object) -> None:
        if getattr(self, "_frozen", False):
            raise AttributeError(f"Shard is immutable — cannot set '{name}' after creation.")
        object.__setattr__(self, name, value)

    def __repr__(self) -> str:
        return (
            f"Shard(id={self.shard_id}, lane={self.lane}, "
            f"tokens={self.token_count}, hash={self.content_hash[:8]})"
        )


def _hash_tokens(token_ids: List[int]) -> str:
    """Stable SHA-256 of the token ID sequence."""
    raw = ",".join(str(t) for t in token_ids)
    return hashlib.sha256(raw.encode()).hexdigest()


# ── Manifest ──────────────────────────────────────────────────────────────────

@dataclass
class ShardManifest:
    shard_id: str
    doc_ids: List[str]
    source: str
    lane: str
    license_tag: str
    tokenizer_hash: str
    cleaning_pipeline_hash: str
    token_count: int
    content_hash: str
    parent_shard_ids: List[str]
    deduplication_status: str = "global_dedup_v1"
    contamination_status: str = "clean"
    eval_overlap_status: str = "no_overlap"
    never_train: bool = False
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        return asdict(self)


def build_manifest(shard: Shard, never_train: bool = False) -> ShardManifest:
    """Create a ShardManifest from a Shard."""
    return ShardManifest(
        shard_id=shard.shard_id,
        doc_ids=shard.doc_ids,
        source=shard.source,
        lane=shard.lane,
        license_tag=shard.license_tag,
        tokenizer_hash=shard.tokenizer_hash,
        cleaning_pipeline_hash=shard.cleaning_pipeline_hash,
        token_count=shard.token_count,
        content_hash=shard.content_hash,
        parent_shard_ids=shard.parent_shard_ids,
        never_train=never_train,
    )


def save_manifest(manifest: ShardManifest, output_dir: Path = MANIFESTS_DIR) -> Path:
    """Write manifest as JSON to the manifests directory."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"{manifest.shard_id}.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(manifest.to_dict(), f, indent=2)
    return path


def load_manifest(shard_id: str, output_dir: Path = MANIFESTS_DIR) -> ShardManifest:
    """Load a manifest from disk."""
    path = output_dir / f"{shard_id}.json"
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    return ShardManifest(**data)


def validate_manifest(shard: Shard, manifest: ShardManifest) -> bool:
    """
    Verify that a shard's content matches its manifest.
    Returns True if valid, raises ValueError if not.
    """
    checks = [
        (shard.shard_id == manifest.shard_id, "shard_id mismatch"),
        (shard.content_hash == manifest.content_hash, "content_hash mismatch"),
        (shard.tokenizer_hash == manifest.tokenizer_hash, "tokenizer_hash mismatch"),
        (shard.token_count == manifest.token_count, "token_count mismatch"),
        (shard.lane == manifest.lane, "lane mismatch"),
    ]
    for passed, msg in checks:
        if not passed:
            raise ValueError(f"Manifest validation failed: {msg} for shard {shard.shard_id}")
    return True
